"""Sync all component versions from the centralized version.json."""

from __future__ import annotations

import json
import re
import shutil
import subprocess
from pathlib import Path

from devops.ui.theme import CYAN, DIM, GREEN, RED, RESET

YELLOW = "\033[93m"


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _read_config() -> dict:
    vf = _repo_root() / "version.json"
    return json.loads(vf.read_text(encoding="utf-8"))


def _write_config(data: dict) -> None:
    vf = _repo_root() / "version.json"
    vf.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _update_package_json(pkg_path: Path, version: str) -> bool:
    """Update the 'version' field in a package.json, return True if changed."""
    if not pkg_path.exists():
        return False
    data = json.loads(pkg_path.read_text(encoding="utf-8"))
    if data.get("version") == version:
        return False
    data["version"] = version
    pkg_path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return True


def _sync_angular_version_ts(version: str) -> bool:
    """Write angular-app/src/version.ts with the given version."""
    out = _repo_root() / "angular-app" / "src" / "version.ts"
    content = f"// Auto-generated by scripts/sync-version.js — do NOT edit manually\nexport const APP_VERSION = '{version}';\n"
    if out.exists() and out.read_text(encoding="utf-8") == content:
        return False
    out.write_text(content, encoding="utf-8")
    return True


def _copy_version_json_to_contexts() -> list[str]:
    """Copy version.json into Docker build sub-contexts."""
    root = _repo_root()
    src = root / "version.json"
    copied: list[str] = []
    for subdir in ["python-api", "angular-app"]:
        dst = root / subdir / "version.json"
        shutil.copy2(str(src), str(dst))
        copied.append(subdir)
    return copied


def sync_versions() -> None:
    """Read version.json and propagate versions to all components."""
    root = _repo_root()
    vf = root / "version.json"

    if not vf.exists():
        print(f"\n  {RED}✗ version.json not found at repo root{RESET}\n")
        return

    data = _read_config()
    app_ver = data["app"]["version"]
    components = data["components"]

    print()
    print(f"  {CYAN}═══ Version Sync ═══{RESET}")
    print(f"  {DIM}Source: version.json → app v{app_ver}{RESET}")
    print()
    print(f"  {'Component':<22} {'Version':<12} {'Action':<40} {'Status'}")
    print(f"  {'─'*22} {'─'*12} {'─'*40} {'─'*10}")

    results: list[tuple[str, str, str, bool]] = []

    # 1. Angular package.json
    ang_ver = components.get("angular-app", app_ver)
    ang_pkg = root / "angular-app" / "package.json"
    changed = _update_package_json(ang_pkg, ang_ver)
    results.append(("Angular FE", ang_ver, "angular-app/package.json", changed))

    # 2. Angular src/version.ts
    changed = _sync_angular_version_ts(ang_ver)
    results.append(("Angular FE", ang_ver, "angular-app/src/version.ts", changed))

    # 3. Nuxt package.json
    nuxt_ver = components.get("nuxt-app", app_ver)
    nuxt_pkg = root / "nuxt-app" / "package.json"
    changed = _update_package_json(nuxt_pkg, nuxt_ver)
    results.append(("Nuxt FE", nuxt_ver, "nuxt-app/package.json", changed))

    # 4. Python API — version read at runtime, nothing to write
    api_ver = components.get("python-api", app_ver)
    results.append(("Python API", api_ver, "reads version.json at runtime", False))

    # 5. DevOps Console — version read at import, refresh module
    devops_ver = components.get("devops", app_ver)
    results.append(("DevOps Console", devops_ver, "reads version.json at import", False))

    # 6. Copy to Docker build contexts
    copied = _copy_version_json_to_contexts()
    for ctx in copied:
        results.append(("Docker ctx", app_ver, f"{ctx}/version.json", True))

    for comp, ver, action, changed in results:
        icon = f"{GREEN}✓ updated{RESET}" if changed else f"{DIM}• current{RESET}"
        print(f"  {comp:<22} {ver:<12} {action:<40} {icon}")

    # 7. Dynamically refresh banner version
    import devops.ui.banner as banner
    banner._VERSION = f"DevOps Console v{devops_ver}"

    print()
    print(f"  {GREEN}✅ All versions synced to v{app_ver}{RESET}")
    print()


def bump_version() -> None:
    """Interactive version bump — prompts for new version, updates version.json,
    then runs sync_versions() to propagate everywhere."""
    data = _read_config()
    current = data["app"]["version"]

    print()
    print(f"  {CYAN}═══ Version Bump ═══{RESET}")
    print(f"  {DIM}Current version: {current}{RESET}")
    print()

    try:
        new_ver = input("  Enter new version (or press Enter to keep current): ").strip()
    except (EOFError, KeyboardInterrupt):
        print(f"\n  {DIM}Cancelled.{RESET}\n")
        return

    if not new_ver:
        print(f"  {DIM}No change.{RESET}\n")
        return

    # Validate semver-ish format
    parts = new_ver.split(".")
    if len(parts) < 2 or not all(p.isdigit() for p in parts):
        print(f"  {RED}✗ Invalid version format. Use semver (e.g. 4.1.0){RESET}\n")
        return

    # Update version.json
    data["app"]["version"] = new_ver
    for comp in data["components"]:
        data["components"][comp] = new_ver
    _write_config(data)

    print(f"  {GREEN}✓ version.json updated: {current} → {new_ver}{RESET}")
    print()

    # Propagate
    sync_versions()


def check_versions() -> None:
    """Read version.json and compare expected versions against actual values
    in every downstream file to detect drift / mismatches."""
    root = _repo_root()
    vf = root / "version.json"

    if not vf.exists():
        print(f"\n  {RED}✗ version.json not found at repo root{RESET}\n")
        return

    data = _read_config()
    app_ver = data["app"]["version"]
    components = data["components"]

    print()
    print(f"  {CYAN}═══ Version Check ═══{RESET}")
    print(f"  {DIM}Source: version.json → app v{app_ver}{RESET}")
    print()
    print(f"  {'Location':<44} {'Expected':<12} {'Actual':<12} {'Status'}")
    print(f"  {'─'*44} {'─'*12} {'─'*12} {'─'*10}")

    mismatches = 0

    def _row(location: str, expected: str, actual: str | None) -> None:
        nonlocal mismatches
        if actual is None:
            icon = f"{YELLOW}⚠ missing{RESET}"
            mismatches += 1
        elif actual == expected:
            icon = f"{GREEN}✓ ok{RESET}"
        else:
            icon = f"{RED}✗ mismatch{RESET}"
            mismatches += 1
        display_actual = actual if actual is not None else "—"
        print(f"  {location:<44} {expected:<12} {display_actual:<12} {icon}")

    # 1. angular-app/package.json
    ang_expected = components.get("angular-app", app_ver)
    ang_pkg = root / "angular-app" / "package.json"
    ang_actual = None
    if ang_pkg.exists():
        ang_actual = json.loads(ang_pkg.read_text(encoding="utf-8")).get("version")
    _row("angular-app/package.json", ang_expected, ang_actual)

    # 2. angular-app/src/version.ts
    vts = root / "angular-app" / "src" / "version.ts"
    vts_actual = None
    if vts.exists():
        m = re.search(r"APP_VERSION\s*=\s*['\"]([^'\"]+)['\"]", vts.read_text(encoding="utf-8"))
        if m:
            vts_actual = m.group(1)
    _row("angular-app/src/version.ts", ang_expected, vts_actual)

    # 3. nuxt-app/package.json
    nuxt_expected = components.get("nuxt-app", app_ver)
    nuxt_pkg = root / "nuxt-app" / "package.json"
    nuxt_actual = None
    if nuxt_pkg.exists():
        nuxt_actual = json.loads(nuxt_pkg.read_text(encoding="utf-8")).get("version")
    _row("nuxt-app/package.json", nuxt_expected, nuxt_actual)

    # 4. python-api/version.json (Docker build context copy)
    api_expected = components.get("python-api", app_ver)
    api_ctx = root / "python-api" / "version.json"
    api_ctx_actual = None
    if api_ctx.exists():
        try:
            api_ctx_actual = json.loads(api_ctx.read_text(encoding="utf-8"))["app"]["version"]
        except (KeyError, json.JSONDecodeError):
            pass
    _row("python-api/version.json (ctx copy)", app_ver, api_ctx_actual)

    # 5. angular-app/version.json (Docker build context copy)
    ang_ctx = root / "angular-app" / "version.json"
    ang_ctx_actual = None
    if ang_ctx.exists():
        try:
            ang_ctx_actual = json.loads(ang_ctx.read_text(encoding="utf-8"))["app"]["version"]
        except (KeyError, json.JSONDecodeError):
            pass
    _row("angular-app/version.json (ctx copy)", app_ver, ang_ctx_actual)

    # 6. devops banner
    devops_expected = components.get("devops", app_ver)
    import devops.ui.banner as banner
    banner_actual = None
    m = re.search(r"v([\d.]+)", banner._VERSION)
    if m:
        banner_actual = m.group(1)
    _row("devops/ui/banner._VERSION", devops_expected, banner_actual)

    # 7. python-api/app/main.py  — check _read_version() source path
    api_main = root / "python-api" / "app" / "main.py"
    api_main_actual = None
    if api_main.exists():
        src = api_main.read_text(encoding="utf-8")
        m = re.search(r'version\s*=\s*["\']([^"\']+)["\']', src)
        if m:
            # static fallback — skip if it reads from version.json dynamically
            api_main_actual = m.group(1)
        # Check for _read_version call which means dynamic
        if "_read_version()" in src:
            api_main_actual = api_ctx_actual or app_ver
            _row("python-api (runtime via version.json)", api_expected, api_main_actual)
        else:
            _row("python-api/app/main.py (hardcoded)", api_expected, api_main_actual)
    else:
        _row("python-api/app/main.py", api_expected, None)

    # Summary
    print()
    if mismatches == 0:
        print(f"  {GREEN}✅ All versions match v{app_ver} — no drift detected{RESET}")
    else:
        print(f"  {RED}⚠  {mismatches} mismatch(es) detected — run {CYAN}Sync Versions{RED} to fix{RESET}")
    print()
