/**
 * sync-version.js — reads ../version.json and writes src/version.ts
 * Run automatically via `prebuild` / `prestart` npm scripts.
 */
const fs = require('fs');
const path = require('path');

// Search paths: repo root (dev) then local copy (Docker build context)
const candidates = [
  path.resolve(__dirname, '..', '..', 'version.json'),   // dev: ../../version.json
  path.resolve(__dirname, '..', 'version.json'),          // Docker: /app/version.json
];
const outFile = path.resolve(__dirname, '..', 'src', 'version.ts');

let version = '0.0.0';
let found = false;
for (const vf of candidates) {
  try {
    const data = JSON.parse(fs.readFileSync(vf, 'utf-8'));
    version = data.components['angular-app'] || data.app.version || version;
    found = true;
    break;
  } catch {
    // try next candidate
  }
}
if (!found) {
  console.warn('⚠ Could not find version.json — using fallback version', version);
}

const content = `// Auto-generated by scripts/sync-version.js — do NOT edit manually
export const APP_VERSION = '${version}';
`;

fs.writeFileSync(outFile, content, 'utf-8');
console.log(`✓ Version synced: ${version} → src/version.ts`);
